project_id = "naijavision"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[auth]
enabled = true
site_url = "https://naijavision.vercel.app"
additional_redirect_urls = [
  "https://naijavision.vercel.app/**",
  "https://judith989.github.io/NaijaVision/**",
  "http://localhost:3000/**"
]
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = true
max_frequency = "1m"
otp_length = 8

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[storage]
enabled = true
file_size_limit = "50MiB"

[functions.tokenize-payout-account]
verify_jwt = true

[functions.process-payment]
verify_jwt = true

[functions.dispatch-quality-control]
verify_jwt = true
